### ISSUE TITLE
Regarding copying unlisenced repository content from Github

### ISSUE THREAD

**Issue by behl1anmol** [beingkS23/ATM-Monitoring-System#2]
Hi,
I see that you and your project contributor @sahaarnav3 have forked my repository **Third-Eye** and copied the following files:

- Readme
- Long Time Pedestrian

Being abide by the laws of code of conduct,  I want to inform you, that legally, without a license, no one can copy the contents of a GitHub repository. You can fork it and view it but not copy its contents.
I request to make suitable changes in your repository to make it free from any similarity with my project.

**Comment by sahaarnav3** [comment]
Removed.
Also can you please check your mail once?
